version: 2
jobs:
  build:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build-production
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@etalab.studio"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "ad:ea:1d:84:0d:44:42:49:e6:c0:f6:1a:28:74:e3:68"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            cd dist &&
            echo csv-gg.etalab.studio > CNAME &&
            gh-pages --message "[skip ci] Updates" --dist .

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
